const Url = {
  login: 'user/login',
  logout: 'user/logout',
  getUserInfo: 'user/userInfo',
  createUser: 'customer/register',
  regions: 'filter/regions',
  home: 'news/home',
  listService: 'service/listService',
  serviceDetail: 'service/serviceDetail',
  review: 'service/review',
  createOrder: 'order/createOrder',
  listOrder: 'customer/listOrder',
  orderDetail: 'order/detail',
  createTransaction: 'order/createTransaction',
  orderCustomer: 'order/orderCustomer',
  customerUpdate: 'customer/update',
  uploadAvatar: 'user/uploadAvatar',
  userReferred: 'user/referred',
  updateIsRead: 'user/updateIsRead',
  createNoti: 'user/createNoti',
  listCate: 'service/listCate',
  newDetail: 'news/newsDetail',
  likeService: 'service/likeService',
  listServiceLiked: 'service/listServiceLiked',
  orderReview: 'order/review',
  transactionDetail: 'order/transactionDetail',
  getListNotif: 'user/getlistNoti',
  createOrderCustomer: 'order/orderCustomerV2',
  deleteOrderCustomer: 'order/deleteOrderCustomer',
  requestPament: 'order/requestPament',
}

export default Url
