const ROUTER = {
  CUSTOMER: '/customer',
  LOGIN: '/dang-nhap',
  OVERVIEW: '/tong-quan',
  USER: '/nguoi-dung',
  SUPPLIER: '/nha-cung-cap',

  ADD_SUPPLIER: '/them-nha-cung-cap',
  EDIT_SUPPLIER: '/sua-nha-cung-cap',

  SUPPLIER_TYPE: '/loai-nha-cung-cap',

  ADD_SUPPLIER_TYPE: '/them-loai-nha-cung-cap',
  EDIT_SUPPLIER_TYPE: '/sua-loai-nha-cung-cap',

  ROOM: '/phong',
  ADD_ROOM: '/them-phong',
  EDIT_ROOM: '/sua-phong',
  EDIT_TOUR: '/sua-tour',
  ADD_TOUR: '/them-tour',
  TOUR: '/tour',
  ROOM_DETAIL: '/chi-tiet-phong',
  ROOM_TYPE: '/loai-phong',

  ACCUMULATION_HISTORY: '/lich-su-tich-diem',
  SYSTEM_LIST: '/danh-sach-he-thong',
  PROVIDER_LIST: '/danh-sach-nha-cung-cap',

  SALE: '/sale',
  ADD_SALE: '/them-sale',
  EDIT_SALE: '/sua-sale',

  ORDER_BOOK_ROOM: '/don-hang-dat-phong',
  ORDER_DETAIL_BOOK_ROOM: '/chi-tiet-don-hang-dat-phong',
  ORDER_DETAIL_BOOK_TOUR: '/chi-tiet-don-hang-dat-tour',
  ADD_ORDER_BOOK_ROOM: '/them-don-hang-dat-phong',
  ADD_ORDER_BOOK_TOUR: '/them-don-hang-dat-tour',
  EDIT_ORDER: '/sua-don-hang',

  SALE_SALES_STATISTICS: '/thong-ke-doanh-so-sale',
  // PARTNER_SALES_STATISTICS: '/thong-ke-doanh-so-doi-tac',
  SETTLEMENT_SALE: '/quyet-toan-sale',
  SETTLEMENT_PROVIDER: '/quyet-toan-provider',
  SETTLEMENT_PROVIDER_DETAIL: '/chi-tiet-quyet-toan-provider',
  SETTLEMENT_SALE_DETAIL: '/chi-tiet-quyet-toan-sale',
  ACCOUNT: '/tai-khoan',
  CHAT_SUPPORT: '/chat-support',
  CHAT_SYSTEM: '/chat-system',
  ORDER_BOOK_TOUR: '/don-hang-dat-tour',
  PROFILE: '/ho-so',
  SUPPORT_CHAT: '/ho-tro-chat',
  NEWS: '/tin-tuc',
  ADD_NEWS: '/them-tin-tuc',
  UPDATE_NEWS: '/sua-tin-tuc',
  NEWS_DETAIL: '/chi-tiet-tin-tuc',
  CONFIG: '/cau-hinh',
  BANK_CONFIG: '/cau-hinh-ngan-hang',
  ORDER_PROVIDER: '/don-hang',
  ACCOUNT_PROVIDER: '/tai-khoan',
  PROVIDER_SALE_LIST: '/chi-tiet-thong-ke-nha-cung-cap',
}
const STRING = {
  changeThePersonInCharge: 'Đổi người phụ trách',
  saleHistory: 'Lịch sử bán hàng',
  score: 'Số điểm',
  chatSystem: 'Chat hệ thống',
  deleteSale: 'Xóa sale',
  orderRoom: 'Đơn hàng đặt phòng',
  orderBookTour: 'Đơn hàng đặt tour',
  tour: 'Tour',
  deposits: 'Cọc chủ nhà',
  unpaid: 'Còn thanh toán chủ nhà',
  home: 'Trang chủ',
  bank: 'Ngân hàng',
  branch: 'Chi nhánh',
  requiredUsername: 'Tên người dùng không được để trống !',
  requiredPassword: 'Mật khẩu không được để trống !',
  productBrand: 'Hãng sản phẩm',
  user: 'Người dùng',
  login: 'Đăng nhập',
  logOut: 'Đăng xuất',
  role: 'Quyền',
  passWord: 'Mật khẩu',
  oldPassword: 'Mật khẩu cũ',
  newPassword: 'Mật khẩu mới',
  confirmPassword: 'Nhập lại mật khẩu mới',
  customer: 'Khách hàng',
  userName: 'Tên người dùng',
  roleName: 'Tên quyền',
  confirmPassWord: 'Xác nhận mật khẩu',
  forgotPass: 'Quên mật khẩu?',
  overView: 'Tổng quan',
  totalProduct: 'Tổng số sản phẩm',
  totalOrders: 'Tổng số đơn hàng',
  approveSuccess: 'Duyệt thành công!',
  approveFail: 'Duyệt thất bại!',
  approve: 'Chấp nhận',
  rejectSuccess: 'Từ chối thành công!',
  rejectFail: 'Từ chối thất bại!',
  addSuccess: 'Thêm thành công!',
  addFail: 'Thêm thất bại!',
  editSuccess: 'Sửa thành công!',
  editFail: 'Sửa thất bại!',
  fail: 'Thất Bại!',
  deleteSuccess: 'Xóa thành công!',
  deleteFail: 'Xóa thất bại!',
  Success: 'Thành công!',
  Fail: 'Thất bại',
  reject: 'Từ chối',
  takeAndReturnPoints: 'Điểm lấy-trả hàng',
  receivingPoint: 'Điểm nhận',
  payPoint: 'Điểm trả',
  profile: 'Hồ sơ',
  typeProfile: 'Loại hồ sơ',
  orderNeedTransport: 'Đơn hàng cần chuyển',
  car: 'Xe',
  addCar: 'Thêm xe',
  carName: 'Tên xe',
  typeCar: 'Loại xe',
  delete: 'Xóa',
  deleteAccount: 'Xóa tài khoản',
  addAccount: 'Thêm tài khoản',
  editAccount: 'Sửa tài khoản',
  name: 'Tên',
  list: 'Danh mục',
  catalogPhoto: 'Ảnh danh mục',
  illustration: 'Ảnh minh họa',
  creator: 'Người tạo',
  action: 'Hành động',
  activing: 'Đang hoạt động',
  stopWorking: 'Ngừng hoạt động',
  active: 'Hoạt động',
  male: 'Nam',
  feMale: 'Nữ',
  notUpdate: 'Chưa cập nhật',
  updating: 'Đang cập nhật',
  updateSuccess: 'Cập nhật thành công',
  updateFail: 'Cập nhật thất bại',
  photoConfirmation: 'Ảnh xác nhận',
  customerDetail: 'Chi tiết khách hàng',
  loading: 'Loading',
  color: 'Màu sắc',
  picture: 'Ảnh',
  order: 'Đơn hàng',
  search: 'Tìm kiếm',
  clearSearch: 'Xóa tìm kiếm',
  add: 'Thêm mới',
  typeName: 'Nhập tên',
  phoneNumber: 'Số điện thoại',
  fromDate: 'Từ ngày',
  toDate: 'Đến ngày',
  status: 'Trạng thái',
  numericalOrder: 'STT',
  fullName: 'Họ tên',
  avatar: 'Ảnh đại diện',
  contentImg: 'Ảnh nội dung',
  specificAddress: 'Địa chỉ cụ thể',
  addressName: 'Tên chi nhánh',
  requiredDistrictCity: 'Tỉnh/Thành phố chưa được chọn!',
  requiredDistrict: 'Quận chưa được chọn!',
  requiredWard: 'Khu vực chưa được chọn!',
  requiredAddress: 'Địa chỉ không được để trống!',
  requiredBranchName: 'Tên chi nhánh không được để trống!',
  requiredPhone: 'Số điện thoại không được để trống!',
  addRole: 'Thêm quyền',
  tabName: 'Tên tab',
  subTab: 'Tab con',
  updateStore: 'Sửa kho',
  toChoose: 'để chọn',
  chooseTab: 'Chọn tab',
  addWarrantyLocation: 'Thêm địa điểm bảo hành',
  updateWarrantyLocation: 'Sửa địa điểm bảo hành',
  typeBranchName: 'Nhập tên chi nhánh',
  branchName: 'Tên chi nhánh',
  numberOfPostingsPerDay: 'Số lần đăng tin mỗi ngày',
  purchase: 'Mua hàng',
  technique: 'Kỹ thuật',
  complaint: 'Khiếu nại',
  email: 'Email',
  address: 'Địa chỉ',
  ok: 'OK',
  addressDetail: 'Địa chỉ chi tiết',
  createDate: 'Ngày tạo',
  bookingDate: 'Ngày đặt',
  checkInDate: 'Ngày nhận phòng',
  checkOutDate: 'Ngày trả phòng',
  full_name: 'Họ và tên',
  inforCustomer: 'Thông tin khách hàng',
  pointPickUp: 'Điểm lấy hàng',
  storeInfomation: 'Thông tin kho hàng',
  pointOfDelivery: 'Điểm trả hàng',
  requestDate: 'Ngày yêu cầu',
  origin: 'Xuất xứ',
  contactPerson: 'Người liên hệ',
  exit: 'Thoát',
  project: 'Dự án',
  area: 'Khu vực',
  companyName: 'Tên công ty',
  projectName: 'Tên dự án',
  priceQuotation: 'Báo giá',
  cost: 'Giá',
  price: 'Giá bán',
  historicalCost: 'Giá gốc',
  payLoad: 'Trọng tải',
  notSoldYet: 'Chưa bán',
  orderStatus: 'Trạng thái đơn',
  refundStatus: 'Trạng thái hoàn tiền',
  inforPriceQuotation: 'Thông tin báo giá',
  vehiclePosting: 'Tin đăng của xe',
  inforTransport: 'Thông tin vận chuyển',
  paymentMethods: 'Phương thức thanh toán',
  inforPayment: 'Thông tin thanh toán',
  change: 'Thay đổi',
  orderInfo: 'Thông tin đơn hàng',
  postingDetail: 'Chi tiết tin đăng',
  schedulingInformation: 'Thông tin đặt lịch',
  news: 'Tin tức',
  discount: 'Khuyến mãi',
  question: 'Câu hỏi',
  config: 'Cấu hình',
  account: 'Tài khoản',
  postNews: 'Đăng tin',
  savedDraft: 'Lưu nháp',
  policy: 'Chính sách và điều khoản',
  chatSupport: 'Chat hỗ trợ',
  connect: 'U- Connect',
  service: 'Dịch vụ',
  addService: 'Thêm dịch vụ',
  addCategories: 'Thêm danh mục',
  editService: 'Sửa dịch vụ',
  deliveryLocation: 'Địa điểm nhận hàng',
  returnsLocation: 'Địa điểm trả hàng',
  warrantyLocation: 'Địa điểm bảo hành',
  chatConfig: 'Cấu hình chat',
  dueDate: 'Ngày quá hạn',
  listName: 'Tên danh mục',
  type: 'Nhập',
  typeGoods: 'Loại hàng',
  major: 'Lĩnh vực',
  object: 'Đối tượng',
  typeNews: 'Loại tin tức',
  banner: 'Banner',
  or: 'hoặc',
  evaluate: 'Đánh giá',
  evaluateAndComment: 'Đánh giá và bình luận',
  buyer: 'Người mua',
  requiredVideoFormat: 'Định dạng video không được hỗ trợ. Vui lòng chọn video khác!',
  driver: 'Tài xế',
  title: 'Tiêu đề',

  titleName: 'Tên tiêu đề',
  postTitle: 'Tiêu đề bài đăng',
  requiredPicture: 'Vui lòng cung cấp hình ảnh!',
  requiredFillInfomation: 'Vui lòng điền đầy đủ thông tin!',
  oldCar: 'Xe cũ',
  emptyData: 'Không có dữ liệu!',
  typeCode: 'Nhập mã',
  addNews: 'Thêm tin tức',
  updateNews: 'Sửa tin tức',
  newsDetail: 'Chi tiết tin tức',
  producer: 'Nhà sản xuất',
  guarantee: 'Bảo hành',
  amount: 'Số lượng',
  // createCategory: 'Thêm dịch vụ',
  editCategory: 'Sửa danh mục',
  editCar: 'Sửa xe',
  taxCode: 'Mã số thuế',
  warehouse: 'Kho hàng',
  productCode: 'Mã sản phẩm',
  saleOff: 'Giảm giá',
  sale: 'Sale',
  saleLead: 'Lead sale',
  addProduct: 'Thêm sản phẩm',
  shortPhone: 'SDT',
  petitioner: 'Người yêu cầu',
  province: 'Tỉnh/ Thành phố',
  district: 'Quận/ Huyện',
  ward: 'Phường xã',
  zone: 'Khu vực',
  supplierType: 'Loại NCC',
  addSupplierType: 'Thêm loại NCC',
  addSupplierTypeFull: 'Thêm loại nhà cung cấp',
  edItSupplierTypeFull: 'Sửa loại nhà cung cấp',
  supplierTypeFull: 'Loại nhà cung cấp',
  supplier: 'Nhà cung cấp',
  addSupplier: 'Thêm NCC',
  addSupplierFull: 'Thêm nhà cung cấp',
  accumulationType: 'Loại tích điểm',
  accumulationHistory: 'Lịch sử tích điểm',
  settlementHistory: 'Lịch sử quyết toán',
  transactionHistory: 'Lịch sử giao dịch',
  score: 'Số điểm',
  accumulationDate: 'Ngày tích điểm',
  salesHistory: 'Lịch sử bán hàng',
  editSupplierFull: 'Sửa nhà cung cấp',
  supplierName: 'Tên nhà cung cấp',
  pack: 'gói',
  ownerName: 'Tên chủ hàng',
  serviceName: 'Tên dịch vụ',
  serviceType: 'Loại dịch vụ',
  typeCategory: 'Loại danh mục',
  changePassWord: 'Đổi mật khẩu',
  notification: 'Thông báo',
  userDetail: 'Chi tiết người dùng',
  sex: 'Giới tính',
  introduce: 'Giới thiệu',
  departmentName: 'Tên căn',
  dateOfBirth: 'Ngày sinh',
  dateSubmitted: 'Ngày đăng',
  imageLogo: 'Ảnh logo (*)',
  boss: 'Chủ hàng',
  carOwner: 'Chủ xe',
  description: 'Mô tả',
  productDescription: 'Mô tả sản phẩm',
  spareInformation: 'Thông tin phụ tùng',
  addLoanCapital: 'Thêm gói vay vốn',
  editLoanCapital: 'Sửa gói vay vốn',
  ProductNumber: 'Số SP',
  infoProjectOwner: 'Thông tin chủ dự án',
  ownerOfProject: 'Chủ dự án',
  vehicleFleetOwner: 'Chủ đội xe',
  personelInfor: 'Thông tin cá nhân',
  carInfor: 'Thông tin xe',
  comment: 'Bình luận',
  productImg: 'Ảnh sản phẩm',
  productVideo: 'Video sản phẩm',
  yearOfManufacture: 'Năm sản xuất',
  specifications: 'Thông số kĩ thuật',
  systemParameter: 'Thông số hệ thống',
  customerName: 'Tên khách hàng',
  orderType: 'Loại hàng',
  representative: 'Người đại diện',
  orderer: 'Người đặt',
  time: 'Thời gian',
  paymentTime: 'Thời gian thanh toán',
  insurancePaymentTime: 'Thời gian thanh toán bảo hiểm',
  defaultPassword: 'Mật khẩu mặc định',

  productList: 'Danh sách sản phẩm',
  packName: 'Tên gói',
  posterTime: 'Thời gian bốc hàng',
  pickUpTime: 'Thời gian lấy hàng',
  orderWeight: 'Khối lượng',
  moneySumOrder: 'Tổng tiền hàng',
  moneySum: 'Tổng tiền',
  paymentSum: 'Tổng thanh toán',
  orderDetail: 'Chi tiết đơn hàng',
  refuse: 'Từ chối',
  accept: 'Chấp nhận',
  pending: 'Chờ duyệt',
  waitForConfirmation: 'Chờ xác nhận',
  approved: 'Đã duyệt',
  pendingProfile: 'Hồ sơ chờ duyệt',
  idCard: 'Chứng minh nhân dân',
  idCardNumber: 'Số CMND/ CCCD',
  saleCommission: 'Hoa hồng',
  upLoad: 'Upload',
  front_idCard: 'Mặt trước CMND',
  back_idCard: 'Mặt sau CMND',
  gplx: 'Giấy phép lái xe',
  multiImage: 'Nhiều ảnh',
  save: 'Lưu',
  assign: 'Chỉ định',
  settlementSaleSuccess: 'Quyết toán thành công',

  assignSuccess: 'Chỉ định thành công!',
  assignFail: 'Chỉ định thất bại!',
  year: ' năm',
  edit: 'Sửa',
  choosenMethod: 'Chọn thao tác',
  carDetail: 'Chi tiết xe',
  reasonForRefusal: 'Lý do từ chối',
  // editCategory: '  Sửa danh mục',

  content: 'Nội dung',
  statusQuo: 'Tình trạng',

  vehiclePostingDetail: 'Chi tiết tin đăng của xe',
  paid: 'Đã thanh toán',
  unPaid: 'Chưa thanh toán',
  delivered: 'Đã giao',
  online: 'online',
  cod: 'Trả sau',
  expiredDate: 'Hạn hoàn thành',
  orderCode: 'Mã đơn hàng',
  UnitPrice: 'Đơn giá',
  intoMoney: 'Thành tiền',
  notEnough: '(Không đủ số lượng)',
  changeAmount: 'Thay đổi số lượng',
  changeStatus: 'Thay đổi trạng thái',
  changeOrderStatus: 'Thay đổi trạng thái đơn hàng',
  changePaymentStatus: 'Thay đổi trạng thái thanh toán',
  blockSuccess: 'Khoá thành công!',
  blockFail: 'Khóa thất bại!',
  videoProduct: 'Video sản phẩm',
  productGroupItem: 'Phân loại hàng',
  productGroupItemPlaceHolder: 'Nhập phân loại hàng, ví dụ: Trắng, Đỏ, v.v',
  productGroupName: 'Tên nhóm phân loại',
  addProductGroup: 'Thêm nhóm phân loại',
  goodsInTheWarehouse: 'Hàng trong kho',
  imageProduct: 'Hình ảnh sản phẩm',
  assignRole: 'Phân quyền',
  all: 'Tất cả',
  skip: 'Bỏ qua',
  video: 'Video',
  addStoreRole: 'Thêm quyền kho',
  deleteStoreRole: 'Xoá quyền kho',
  completed: 'Hoàn thành',
  individual: 'Cá nhân',
  enterprise: 'Doanh nghiệp',
  infoProduct: 'Thông tin sản phẩm',
  applyForAll: 'Áp dụng tất cả',
  userInfo: 'Thông tin người dùng',
  formality: 'Hình thức',
  paymentStatus: 'Trạng thái thanh toán',
  productBrandImage: 'Ảnh hãng',
  refund: 'Đã hoàn tiền',
  image: 'Ảnh',

  unlockCustomer: 'Mở khóa',
  unlockSuccess: 'Mở khóa thành công',
  unlockFail: 'Mở khóa thất bại',
  locked: 'Bị khóa',

  timeToSetOrder: 'Thời gian đặt hàng',
  timeToGetOrder: 'Thời gian nhận hàng',
  numberOfProduct: 'Số sản phẩm',
  productType: 'Loại sản phẩm',
  integratedShipping: 'Tích hợp vận chuyển',
  blockAccount: 'Khóa tài khoản',
  openAccount: 'Mở khóa tài khoản',
  isLocked: 'Bị khóa',
  storeConfirm: 'Kho xác nhận',
  storeStatus: 'Tình trạng kho',
  storeConfirmed: 'Kho đã xác nhận',
  storeNotConfirmed: 'Kho chưa xác nhận',
  processing: 'Đang xử lý',
  processed: 'Đã xử lý',
  editProduct: 'Sửa sản phẩm',
  productDetail: 'Chi tiết sản phẩm',
  length: 'Dài',
  width: 'Rộng',
  height: 'Cao',
  priority: 'Ưu tiên',
  numberOfVehicle: 'Số lượng xe',
  accountNumber: 'Số tài khoản',
  cancel: 'Hủy',
  nameType: 'Tên loại',
  roomTypeName: 'Tên loại phòng',
  room: 'Phòng',
  addRoom: 'Thêm phòng',
  roomName: 'Tên phòng',
  roomType: 'Loại phòng',
  roomCode: 'Mã phòng',
  serviceCharge: 'Dịch vụ tính phí',
  roomOwner: 'Chủ phòng',
  roomPhoto: 'Ảnh phòng',
  videoRoom: 'Video phòng',
  addRoomType: 'Thêm loại phòng',
  editRoomType: 'Sửa loại phòng',
  statistical: 'Thống kê',
  systemList: 'DS hệ thống',
  supplierList: 'DS nhà cung cấp',
  saleList: 'DS sale',
  partnerList: 'DS đối tác',
  providerList: 'DS nhà cung cấp',
  sale: 'Sale',
  addSale: 'Thêm sale',
  editSale: 'Sửa sale',
  man: 'Nam',
  women: 'Nữ',
  addOrder: 'Thêm đơn',
  numberOfGuests: 'Số lượng khách',
  adults: 'Người lớn',
  children: 'Trẻ em',
  typeNumber: 'Nhập số',
  dateOfDepartment: 'Ngày đi',
  returnDate: 'Ngày về',
  note: 'Ghi chú',
  age: 'Tuổi',
  partnerSalesStatistics: 'Thống kê doanh số đối tác',
  saleSalesStatistics: 'Thống kê doanh số sale',
  accountType: 'Loại tài khoản',
  systemParameters: 'Thông số hệ thống',
  sampleMessage: 'Tin nhắn mẫu',
  tourName: 'Tên tour',
  inCharge: 'Phụ trách',
  numberPeople: 'Số người',
  checkInOut: 'Nhận - trả phòng',
  responsibleSale: 'Sale phụ trách',
  responsibleLead: 'Lead phụ trách',
  amountMoney: 'Số tiền',
  pileDate: 'Ngày cọc',
  transferDate: 'Ngày CK',
  cancelOrder: 'Hủy đơn',
  transferImage: 'Ảnh CK',
  smsMoneyBack: 'SMS tiền về',
  smsImageMoneyBack: 'Ảnh SMS tiền về',
  smsImage: 'Ảnh SMS',
  bookRoom: 'Đặt phòng',
  partialPile: 'Cọc một phần',
  payOff: 'Trả hết',
  update: 'Cập nhập',
  houseCode: 'Mã căn',
  editProvider: 'Sửa nhà cung cấp',
  supplierTypeName: 'Tên loại nhà cung cấp',
  editRoom: 'Sửa phòng',
  sales: 'Doanh số',
  displayIndex: 'Thứ tự hiển thị',
  editNews: 'Sửa tin tức',
  addTour: 'Thêm tour',
  tourCode: 'Mã tour',
  tourOwner: 'Chủ tour',
  editTour: 'Sửa tour',
  tourPhoto: 'Ảnh tour',
  videoTour: 'Video tour',
  model: 'Mô hình',
  bookTour: 'Đặt tour',
  settlementSale: 'Quyết toán sale',
  settlement: 'Quyết toán',
  notAssigned: 'Số đơn chưa chỉ định',
  notFinish: 'Số đơn chưa hoàn thành',
  finished: 'Số đơn đã hoàn thành',
  totalCustomer: 'Tổng khách hàng',
  addSampleMessage: 'Thêm tin nhắn mẫu',
  editSampleMessage: 'Sửa tin nhắn mẫu',
  saleDetail: 'Chi tiết sale',
}

const TYPE_INPUT = {
  text: 1,
  select: 2,
  multiselect: 3,
  radio: 4,
  number: 5,
  passWord: 6,
  email: 7,
  file_front: 8,
  file_back: 9,
  multiImage: 10,
  text_description: 11,
  icon_url: 12,
  illustration: 13,
  textConvertToNumber: 14,
  checkbox: 15,
  date: 16,
  phoneNumber: 17,
  autoComplete: 18,
}

const STATUS = {
  pending: 0,
  approve: 1,
  stopWorking: 2,
  sold: 3,
}

const CUSTOMERS_STATUS = {
  pending: 0,
  active: 1,
  block: 2,
}

const ORDER_STATUS = {
  REJECTED: -1,
  CUSTOMER_CREATED: 1,
  ADMIN_CONFIRMED: 2,
  CHANGE_TO_SALE_LEADER: 3,
  CHANGE_TO_SALE: 4,
  SALE_CONFIRMED: 5,
  CHECK_IN: 6,
  CHECK_OUT: 7,
  SALE_REJECTED: 8,
  FINISHED: 10,
}

const NEWS_STATUS = {
  POSTING: 1,
  DRAFT: 2,
}

const SETTLEMENT_SALE_STATUS = {
  SETTLEMENT: 1,
  NOT_SETTLEMENT: 0,
}

const ORDER_STATUS_LIST = [
  { id: -1, name: 'Hủy bỏ' },
  { id: 1, name: 'Chờ xác nhận' },
  { id: 2, name: 'Admin xác nhận' },
  { id: 3, name: 'Chỉ định cho sale leader' },
  { id: 4, name: 'Chỉ định cho sale' },
  { id: 5, name: 'Sale xác nhận' },
  { id: 6, name: 'Check in' },
  { id: 7, name: 'Check out' },
  { id: 10, name: 'Hoàn thành' },
]

const PAYMENT_STATUS_LIST = [
  { id: -1, name: 'Thanh toán lỗi' },
  { id: 1, name: 'Chưa trả' },
  { id: 2, name: 'Đã đặt cọc' },
  { id: 3, name: 'Đặt cọc thành công' },
  { id: 10, name: 'Đã thanh toán hết' },
]

const PAYMENT_STATUS = {
  FALSE: -1, // thanh toán lỗi
  UNPAID: 1, // chưa thánh toán
  NOT_PAID_OFF: 2, // đã đặt cọc
  PAID: 3, // đặt cọc thành công
  SUCCESS: 4, // đặt cọc thành công
  ACCEPT_FOR_DESPOSIT: 5, // cho phép đặt cọc
  DESPOSIT_SUCCESS: 6, // đặt cọc thành công dữ chỗ cho khách
  CAN_CHECK_IN: 7, //có thế check in được
  SUCCESS_ALL: 10,
}

const ORDER_PROVIDER_STATUS = {
  ORDER_WAITING: 1,
  ORDER_PROCESSING: 2,
  ORDER_HISTORY: 3,
}

const ORDER_PROVIDER_LIST = [
  {
    id: 1,
    name: 'Chờ xác nhận',
  },
  {
    id: 2,
    name: 'Đang thực hiện',
  },
  {
    id: 3,
    name: 'Hoàn thành/Hủy',
  },
]

const ROLE = {
  ADMIN: 1,
  PROVIDER: 2,
  SALE: 3,
  CUSTOMER: 4,
  SALE_LEADER: 5,
  ACCOUNTANT: 6,
  EDITOR: 7,
}

const PAYMENT_TYPE = {
  online: 1,
  cod: 2,
}

const NUMBER = {
  page_limit: 12,
}

const LABEL_BUTTON_SEARCH = {
  lable: 'Tìm kiếm',
  variant: 'success',
  style: '',
}

const LABEL_BUTTON_CLEAR_SEARCH = {
  lable: 'Xóa tìm kiếm',
  variant: 'secondary',
  style: '',
}

const LABLE_BUTTON_UPDATE = {
  lable: 'Cập nhật',
  variant: 'success',
  style: '',
}

const LABEL_BUTTON_ADD = {
  lable: 'Thêm mới',
  variant: 'primary',
  style: '',
}
const LABLE_BUTTON_SYNCHRONIZED = {
  lable: 'Đồng bộ',
  variant: 'danger',
  style: '',
}
const LABEL_BUTTON_REJECT = {
  lable: 'Từ chối',
  variant: 'danger',
  style: '',
}
const LABEL_BUTTON_CONFIRM = {
  lable: 'Chấp nhận',
  variant: 'success',
  style: '',
}
const LABEL_BUTTON_SAVE = {
  lable: 'Lưu',
  variant: 'success',
  style: '',
}
const LABEL_BUTTON_CANCEL = {
  lable: 'Hủy',
  variant: 'danger',
  style: '',
}
const LABLE_BUTTON_APPROVE = {
  lable: 'Duyệt',
  variant: 'success',
  style: '',
}
const LABLE_BUTTON_LOCK_ACCOUNT = {
  lable: 'Khóa tài khoản',
  variant: 'danger',
  style: '',
}
const LABLE_BUTTON_STOP_ACTIVE = {
  lable: 'Ngưng hoạt động',
  variant: 'warning',
  style: '',
}
const LABLE_BUTTON_BACK = {
  lable: 'Trở lại',
  variant: 'danger',
  style: '',
}

const ACCEPT_TYPE = {
  IMAGE: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
  DOCUMENT: ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
  VIDEO: ['video/mp4', 'video/ogg', 'video/webm'],
}

const TRANSACTION_STATUS = {
  DEPOSIT_CUSTOMER: 1,
  PAY_OFF: 2,
  DECISION_CUSTOMER: 3,
  DEPOSIT_HOME_OWNER: 4,
  MONEY_LEFT_TO_PAY_HOME_OWNER: 5,
  MONEY_LEFT_TO_PAY_CUSTOMER: 6,
}

const MEDIA_TYPE = {
  IMAGE: 1,
  VIDEO: 2,
}

const USER_HISTORY_TYPE = {
  PROFIT: 1, // cộng điểm khi hoàn thành đơn
  USE_POINT: 2, // dùng điểm
  ROLL_BACK: 3, // trả lại điểm
  PAYMENT: 4, // trừ điểm khi quyết toán
  INVITE: 5, // cộng điểm khi giới thiệu app
}

const USER_HISTORY_LIST = [
  {
    id: 1,
    name: 'Cộng điểm khi hoàn thành đơn',
  },
  {
    id: 2,
    name: 'Dùng điểm',
  },
  {
    id: 3,
    name: 'Trả lại điểm',
  },
  {
    id: 4,
    name: 'Trừ điểm khi quyết toán',
  },
  {
    id: 5,
    name: 'Cộng điểm khi giới thiệu app',
  },
]

const CHAT_STATUS = {
  SALE_LEADER_CONFIRMED: 1,
  ADMIN_CHAT: 2,
  CUSTOMER_CHAT: 20,
  DEPOSIT_CUSTOMER: 6,
  PAYMENT_CUSTOMER: 9,
  NEW_ORDER: 10,
  CUSTOMER_CHAT_TO_SALE: 11,
  ORDER_PRICE: 21,
  CHECK_IN_OR_CHECK_OUT: 22,
  UPDATE_TO_HOMEOWNER: 23,
  KEEP_ORDER: 25,
  CAN_CHECK_IN: 26,
  ALLOW_DEPOSIT: 27,
  UPDATE_CUSTOMER: 28,
  REQUIRED_DEPOSIT: 29,
}

const NOTI_TYPE = {
  ORDER_BOOK_ROOM_LIST: 1,
  ORDER_DETAIL_BOOK_ROOM: 2,
  ORDER_BOOK_TOUR_LIST: 3,
  ORDER_DETAIL_BOOK_TOUR: 4,
}

export {
  ROUTER,
  STRING,
  NUMBER,
  LABEL_BUTTON_SEARCH,
  LABEL_BUTTON_ADD,
  LABLE_BUTTON_UPDATE,
  LABEL_BUTTON_CLEAR_SEARCH,
  LABLE_BUTTON_SYNCHRONIZED,
  LABEL_BUTTON_CONFIRM,
  LABEL_BUTTON_REJECT,
  LABLE_BUTTON_BACK,
  LABLE_BUTTON_LOCK_ACCOUNT,
  LABLE_BUTTON_STOP_ACTIVE,
  LABLE_BUTTON_APPROVE,
  LABEL_BUTTON_SAVE,
  LABEL_BUTTON_CANCEL,
  TYPE_INPUT,
  STATUS,
  ACCEPT_TYPE,
  ORDER_STATUS,
  ORDER_STATUS_LIST,
  PAYMENT_STATUS,
  PAYMENT_STATUS_LIST,
  CUSTOMERS_STATUS,
  PAYMENT_TYPE,
  ROLE,
  TRANSACTION_STATUS,
  MEDIA_TYPE,
  NEWS_STATUS,
  USER_HISTORY_TYPE,
  USER_HISTORY_LIST,
  SETTLEMENT_SALE_STATUS,
  CHAT_STATUS,
  ORDER_PROVIDER_LIST,
  ORDER_PROVIDER_STATUS,
  NOTI_TYPE,
}
