version: "3.7"
x-restart-policy: &restart-policy
  restart: always
x-default-env-file: &env-file
  env_file:
    - .env

services:
  database:
    <<: *restart-policy
    <<: *env-file
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./DB/conf.d/:/etc/mysql/conf.d/
      - ./DB/init:/docker-entrypoint-initdb.d
      - ./DB/data:/var/lib/mysql
