version: "3.8"

x-restart-policy: &restart-policy
  restart: always
x-default-env-file: &env-file
  env_file:
    - .env

services:
  ohotour_db:
    container_name: ohotour_db
    command: --default-authentication-plugin=mysql_native_password
    # cấu hình vị trí file Dockerfile để build
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - 8667:3306
    volumes:
      # cau hinh mysql (phan biet hoa thường, ký tự tiếng việt....)
      - "./DB/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      #luu du lieu ra folder data cua may host
      - ./DB/data:/var/lib/mysql
      # du lieu mac dinh khi khoi tao container (import tu file .sql)
      - ./DB/init:/docker-entrypoint-initdb.d
    networks:
      - mynet

  ohotour_server:
    build: ./API
    environment:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./API/dist/uploads:/app/dist/uploads
    networks:
      - mynet
    command: yarn start

  web_admin:
    container_name: ohotour_web_admin
    build: ./WEB/WEB_ADMIN
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
    networks:
      - mynet

  web_customer:
    container_name: ohotour_web_customer
    build: ./WEB/WED_CUSTOMER
    ports:
      - ${CUSTOMER_PORT}:${CUSTOMER_PORT}
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
