version: "3.8"

x-restart-policy: &restart-policy
  restart: always
x-default-env-file: &env-file
  env_file:
    - .env

services:
  ohotour_db:
    container_name: ohotour_db
    command: --default-authentication-plugin=mysql_native_password
    # cấu hình vị trí file Dockerfile để build
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - 8667:3306
    volumes:
      # cau hinh mysql (phan biet hoa thường, ký tự tiếng việt....)
      - "./DB/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      #luu du lieu ra folder data cua may host
      - ./DB/data:/var/lib/mysql
      # du lieu mac dinh khi khoi tao container (import tu file .sql)
      - ./DB/init:/docker-entrypoint-initdb.d
    networks:
      - mynet

  ohotour_server:
    build: ./API
    depends_on:
      - ohotour_db
    environment:
      - NODE_ENV=production
      - PORT=8700
      - WAIT_HOSTS=ohotour_db:3306
      - DB_HOST=ohotour_db
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - SECRET=${SECRET}
      - DB_NAME=tacn
    ports:
      - 8700:8700
    volumes:
      - ./API/dist/uploads:/app/dist/uploads
    networks:
      - mynet
    command: yarn start

  web:
    container_name: ohotour_web_admin
    build:
      context: ./WEB/WEB_ADMIN
      dockerfile: Dockerfile
    depends_on:
      - ohotour_server
    ports:
      - 3333:80
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
